name: Scheduled Tasks - Check Expired Subscriptions

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  check-expired-subscriptions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Expired Subscriptions
        run: |
          echo "Checking expired subscriptions..."
          
          # Call the scheduled tasks Edge Function
          response=$(curl -s -w "%{http_code}" -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/scheduled-tasks" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -H "X-Cron-Secret: ${{ secrets.CRON_SECRET_TOKEN }}" \
            -d '{"source": "github_actions"}')
          
          http_code="${response: -3}"
          response_body="${response%???}"
          
          echo "HTTP Status: $http_code"
          echo "Response: $response_body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "❌ Scheduled task failed with status $http_code"
            exit 1
          else
            echo "✅ Scheduled task completed successfully"
          fi

      - name: Verify Results
        run: |
          echo "Verifying subscription cleanup..."
          
          # Optional: Call a verification endpoint to check results
          curl -s -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/check-expired-subscriptions" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"verify_only": true}' || echo "Verification endpoint not available"