import { Link } from 'react-router-dom';
import { ArrowLeft, AlertTriangle } from 'lucide-react';

const Disclaimer = () => {
  return (
    <div className="py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center mb-8">
          <Link 
            to="/" 
            className="flex items-center text-gray-600 hover:text-gray-900 mr-4"
          >
            <ArrowLeft className="h-5 w-5 mr-1" />
            Back to Home
          </Link>
          <div className="flex items-center">
            <AlertTriangle className="h-6 w-6 text-blue-800 mr-2" />
            <h1 className="text-3xl font-bold text-gray-900">Disclaimer</h1>
          </div>
        </div>

        <div className="prose prose-lg max-w-none">
          <p className="text-gray-600 mb-8">
            <strong>Last updated:</strong> June 13, 2025
          </p>

          <div className="space-y-8">
            <section className="mb-8">
              <p className="text-gray-700 mb-4">
                This Disclaimer governs your use of the website and services provided by SEO Snap ("we," "us," or "our") at www.seosnap.com. By accessing or using our platform, you acknowledge and agree to the terms set forth in this Disclaimer. If you do not agree, do not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. No SEO Guarantee</h2>
              <p className="text-gray-700 mb-4">
                SEO Snap is a tool that utilizes artificial intelligence to generate metadata—including SEO titles, meta descriptions, and tags—based on user-submitted images. While our Service is designed to assist with search engine optimization (SEO) efforts, we do not guarantee any specific outcomes, such as improved search rankings, increased website traffic, or conversions.
              </p>
              <p className="text-gray-700 mb-4">
                Search engine results are influenced by a wide range of external factors beyond our control, including search engine algorithms, competition, user behavior, and website structure.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Informational Use Only</h2>
              <p className="text-gray-700 mb-4">
                All content generated or provided by SEO Snap is for informational and illustrative purposes only. You are solely responsible for reviewing, editing, and determining the suitability of any metadata generated by our AI before using it in a live environment. We make no representations regarding legal compliance, accuracy, completeness, or fitness for a specific use case.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. No Professional Advice</h2>
              <p className="text-gray-700 mb-4">
                The outputs and suggestions provided through our Service do not constitute professional marketing, legal, or technical advice. You should consult qualified professionals before implementing any major content or SEO strategies based on information generated through SEO Snap.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Use at Your Own Risk</h2>
              <p className="text-gray-700 mb-4">
                You assume full responsibility for your use of the metadata or content generated by our AI. SEO Snap is not liable for any direct or indirect damages—including loss of business, data, revenue, or reputation—that may result from the use or misuse of our Service.
              </p>
              <p className="text-gray-700 mb-4">
                You also understand that:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4">
                <li>The quality of AI-generated content may vary</li>
                <li>Results may contain inaccuracies or require human editing</li>
                <li>You should verify that any output complies with applicable laws, platform policies, and SEO best practices</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Third-Party Links and Content</h2>
              <p className="text-gray-700 mb-4">
                Our Service may include links to third-party sites or tools. We do not endorse or control these third-party resources and are not responsible for their content, terms, or privacy practices.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Intellectual Property and User Responsibility</h2>
              <p className="text-gray-700 mb-4">
                By uploading any content (e.g., images), you represent that you have the legal right to use and share that material. SEO Snap is not responsible for content submitted without proper authorization or that may infringe on third-party rights.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Changes to Disclaimer</h2>
              <p className="text-gray-700 mb-4">
                We reserve the right to update this Disclaimer at any time without prior notice. Updates will be posted on this page with a new "Last Updated" date. Continued use of the Service after such updates constitutes acceptance.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;